### ISSUE TITLE
UI is not good my dear 

### ISSUE THREAD

**Issue by ramakrishnabest** [JeevantheDev/Doctor-Assigned#2]
UI is not good my friend i saw your screens

**Comment by JeevantheDev** [comment]
Which route UI is not good ?

**Comment by ramakrishnabest** [comment]
fronted booking

**Comment by JeevantheDev** [comment]
Can you give any idea what to improve ?

**Comment by ramakrishnabest** [comment]
yes for sure and also frontend booking also not working as well as
https://pacific-bastion-55341.herokuapp.com/profiles

**Comment by JeevantheDev** [comment]
Booking Appointment will be work after login as user.

**Comment by ramakrishnabest** [comment]
what about the guest. I am sorry for asking many questions i have been using wordpress appointment plugin science 3 years so i am just giving you ideas pls dont mind

**Comment by JeevantheDev** [comment]
Ok Ok no Problem

**Comment by JeevantheDev** [comment]
You can register as a user and book your appointment after login as a user.

**Comment by JeevantheDev** [comment]
I have build this using MERN stack.

**Comment by ramakrishnabest** [comment]
thats great started eith passion or just for normal ?

**Comment by JeevantheDev** [comment]
Actually I was learning MERN stack from a tutorial, after complete that tutorial I have build this.

**Comment by ramakrishnabest** [comment]
good knowledge in PHP also ?

**Comment by JeevantheDev** [comment]
No no I have only idea in React.js, Next.js ,Node.js, Express.js, Prisma and MongoDB

**Comment by ramakrishnabest** [comment]
doing job some where ?

**Comment by JeevantheDev** [comment]
No no I am in my undergrad B.Tech CSE 3rd year

**Comment by JeevantheDev** [comment]
What's about you ?

**Comment by ramakrishnabest** [comment]
i started my own startup with 2 friends

**Comment by JeevantheDev** [comment]
Ohh nice. which tech stack are you use ?

**Comment by JeevantheDev** [comment]
Which tech stack do you use ?

**Comment by ramakrishnabest** [comment]
php mainly

**Comment by JeevantheDev** [comment]
Ok, Nice to talk with you.

**Comment by ramakrishnabest** [comment]
me too  there is a hues market if you do great appointment one

**Comment by JeevantheDev** [comment]
ok
